name: reusable deploy
on:
  workflow_call:
    inputs:
      artifacts-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifacts-name }}
      - name: list files
        run: ls
      - name: Output information
        run: echo "Deploying & uploading"