name: reusable deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: the result of deploy
        value: ${{ jods.deploy.outputs.outcome }}
      # secrets:
      #   some-secret:
      #     required: false
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifacts-name }}
      - name: list files
        run: ls
      - name: Output information
        run: echo "Deploying & uploading"
      - name: set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
